### PR TITLE
Add Groestlcoin and Groestcoin Testnet with correct Base58 hash

### PR DESCRIPTION
**Pull request by HashEngineering**
After submitting this, I realized that my editor reformatted index.js.  Let me know if you want me to undo those changes.

### CODE REVIEW

**Comment by gruve-p** [comment]
Can this be merged?

**Comment by erasmospunk** [comment]
Thanks for the PR. Have you considered to also push this to the [upstream project](https://github.com/iancoleman/bip39)?

**Comment by gruve-p** [comment]
No we did not consider that. Coinomi requested our help to implement GRS in the BIP39 tool hence this PR. The scope of this PR is that Coinomi users are able to extract private keys for Groestlcoin.

**Comment by erasmospunk** [comment]
Thank you for the PR!

Please make this PR to the upstread project https://github.com/iancoleman/bip39.

We are contributing there now.

**Comment by HashEngineering** [comment]
Thanks, I will do that.

**Pull request closed without merging**
